#!/bin/bash

# Runs multiple games with specified brokers
#
# Usage:
#  run-sims [-c config] [-s start-count] count broker ...

# Strip off options
config=''
offset=1
while getopts ":c:s:" opt ; do
    case $opt in
	c  ) config="--config $OPTARG" ;;
	s  ) offset=$OPTARG ;;
	\? ) echo 'usage: run-sims [-c config] [-s start-count] n broker ...'
	     exit 1
    esac
done
shift $(($OPTIND - 1))

num=$1
shift

let y=0
while [ $y -lt $num ] ; do
    x=$(($y + $offset))
    # boot session first
    mvn -Pcli -Dexec.args="--boot boot-g${x}.xml --log-suffix boot-${x} $config"
    tar czf game-${x}-boot-logs.tar.gz log/powertac-boot-${x}.state log/powertac-boot-${x}.trace
    rm log/powertac-boot-${x}.state log/powertac-boot-${x}.trace

    # followed by sim session
    mvn -Pcli -Dexec.args="--sim --boot-data boot-g${x}.xml --log-suffix sim-${x} $config --brokers $@"
    tar czf game-${x}-sim-logs.tar.gz log/powertac-sim-${x}.state log/powertac-sim-${x}.trace
    rm log/powertac-sim-${x}.state log/powertac-sim-${x}.trace

    let y=y+1
done
